# Generated by Django 4.1.3 on 2022-12-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='team_a_goals',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_goals',
            field=models.IntegerField(default=0),
        ),
    ]
