# Generated by Django 4.1.3 on 2022-12-03 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_match_team_a_goals_alter_match_team_b_goals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_date',
            field=models.DateTimeField(verbose_name='Data/Hora do jogo'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_a_matches', to='app.team', verbose_name='Time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_a_goals',
            field=models.IntegerField(default=0, verbose_name='Gols do Time A'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='team_b_matches', to='app.team', verbose_name='Time B'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_b_goals',
            field=models.IntegerField(default=0, verbose_name='Gols do Time B'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='myteam',
            name='players',
            field=models.ManyToManyField(to='app.player', verbose_name='Jogadores'),
        ),
        migrations.AlterField(
            model_name='player',
            name='initial_price',
            field=models.FloatField(verbose_name='Preço inicial'),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
