# Generated by Django 4.1.3 on 2022-12-04 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_match_options_alter_myteam_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutes', models.IntegerField(verbose_name='Minutos')),
                ('action', models.CharField(choices=[('goal', 'Gol'), ('assist', 'Assistência'), ('yellow card', 'Cartão Amarelo'), ('red card', 'Cartão Vermelho')], max_length=50, verbose_name='Ação')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.match', verbose_name='Jogo')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.player', verbose_name='Jogador')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.team', verbose_name='Time')),
            ],
            options={
                'verbose_name': 'Ação do Jogo',
                'verbose_name_plural': 'Ações do Jogo',
            },
        ),
    ]
